# Hugging Face Set Up

In [1]:
# run the first time
#!pip install datasets
#!python -c "from datasets import load_dataset; print(load_dataset('squad', split='train')[0])"
#!git clone https://github.com/huggingface/datasets.git
#!pip install -e datasets/ 
#!python -c "from datasets import load_dataset; print(load_dataset('squad', split='train')[0])"

# Load Data from Hugging Face
[config info](https://huggingface.co/datasets/peixian/rtGender/blob/main/rtGender.py)

In [2]:
# run the first time
# from datasets import get_dataset_config_names

# configs = get_dataset_config_names('peixian/rtGender')
# print(configs)

In [3]:
from datasets import load_dataset
posts = load_dataset('peixian/rtGender', 'posts', split = 'train')
print(posts)
posts[0]

Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/posts/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)


Dataset({
    features: ['source', 'op_id', 'op_gender', 'post_id', 'post_text', 'post_type', 'subreddit', 'op_gender_visible'],
    num_rows: 2469836
})


{'source': '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_posts',
 'op_id': '57265377',
 'op_gender': 'M',
 'post_id': '0000000',
 'post_text': "Yesterday, my colleagues and I voted to protect state's rights and the rights of our unborn children by overturning Obama's HHS rule. I pledge to always protect the sanctity of life. https://goo.gl/N8kd99",
 'post_type': 'video',
 'subreddit': None,
 'op_gender_visible': None}

In [4]:
responses = load_dataset('peixian/rtGender', 'responses', split = 'train')
print(responses)
responses[:10]

Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/responses/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)


Dataset({
    features: ['source', 'op_id', 'op_gender', 'post_id', 'responder_id', 'response_text', 'op_name', 'op_category', 'responder_gender', 'responder_gender_visible', 'subreddit'],
    num_rows: 26496468
})


{'source': ['/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg/.cache/huggingface/datasets/downloads/extracted/2a2b549303f3c7cbf8b1989705b31377e104d11b1a2af73c46c2c726e0b54b3a/facebook_congress_responses',
  '/home/kbaumberg

In [5]:
annotations = load_dataset('peixian/rtGender', 'annotations', split = 'train')
print(annotations)
annotations[:10]

Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/annotations/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)


Dataset({
    features: ['source', 'op_gender', 'post_text', 'response_text', 'sentiment', 'relevance'],
    num_rows: 15352
})


{'source': ['facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki',
  'facebook_wiki'],
 'op_gender': ['W', 'M', 'W', 'M', 'W', 'M', 'W', 'W', 'W', 'W'],
 'post_text': ["Stopped by Fashion Week and got to hang with Amber Fillerup (Barefoot Blonde) at Lauren Conrad's runway show. Kohl's #LCRunway",
  "Well guys, real progress is happening. I'm 50 pages in and the story is really starting to get under my skin. It's all tingly...",
  'Tonight is going to be a good night #PerfectMoment #BeautifulNight #OlympicGames #OpeningCeremony',
  'I know grandma Gilmore is real proud of you https://t.co/oRtvR2YuQ2',
  "#NEWS to KNOW this AM - Mayor Emanuel will make a special address today on police accountability...The third suspect in last month's #Paris attacks has been identified...#Teachers start voting today on a possible strike.",
  "What questions do you have for Alisyn Camerota? L

# RtGender Data Loading Into Tensorflow

In [6]:
# run the first time you run this notebook
#!pip install transformers

[Source code](https://www.kaggle.com/nkaenzig/bert-tensorflow-2-huggingface-transformers)

In [59]:
import tensorflow as tf
from tf import keras

from datasets import load_dataset
from transformers import AutoTokenizer


Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/posts/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)
Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/posts/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)


In [62]:
response_train = load_dataset('peixian/rtGender', 'posts', split = 'train[:900]')
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
dataset = response_train.map(lambda e: tokenizer(e['post_text'], truncation=True, padding='max_length'), batched=True)
dataset.set_format(type='tensorflow', columns=['input_ids', 'token_type_ids', 'attention_mask', 'op_gender'])
features = {x: dataset[x].to_tensor(default_value=0, shape=[None, tokenizer.model_max_length]) for x in ['input_ids', 'token_type_ids', 'attention_mask']}
tfdataset = tf.data.Dataset.from_tensor_slices((features, dataset["op_gender"])).batch(32)
next(iter(tfdataset))

Reusing dataset rt_gender (/home/kbaumberg/.cache/huggingface/datasets/rt_gender/posts/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1)
Loading cached processed dataset at /home/kbaumberg/.cache/huggingface/datasets/rt_gender/posts/1.1.0/62d8f34778a4eda10ed650d804cbb7ad4da391ac28f38034f424a2e9a7fc43d1/cache-375a24b39d0fd3dd.arrow


({'input_ids': <tf.Tensor: shape=(32, 512), dtype=int64, numpy=
  array([[  101, 21997,   117, ...,     0,     0,     0],
         [  101, 17303,  1132, ...,     0,     0,     0],
         [  101,   108,   157, ...,     0,     0,     0],
         ...,
         [  101,  1622,  1412, ...,     0,     0,     0],
         [  101,  3570,   117, ...,     0,     0,     0],
         [  101, 13832, 18734, ...,     0,     0,     0]])>,
  'token_type_ids': <tf.Tensor: shape=(32, 512), dtype=int64, numpy=
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])>,
  'attention_mask': <tf.Tensor: shape=(32, 512), dtype=int64, numpy=
  array([[1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         ...,
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0

In [ ]:
response_valid = load_dataset('peixian/rtGender', 'posts', split = 'train[901:1000]')
